% Create a rectangularArray with patchMicrostrip element.
% Generated by MATLAB(R) 9.8 and Antenna Toolbox 4.2.
% Generated on: 14-Jan-2021 17:11:41

%% Array Properties 
%Define Array
arrayObject = rectangularArray;

arrayObject.Size = [2  2];

%Define Array Elements
Element1 = patchMicrostrip;
arrayObject.Element = [Element1 ];

% Design array at frequency 1500000000Hz
arrayObject = design(arrayObject,1500000000,Element1);
%arrayObject Properties Changed
arrayObject.RowSpacing = 0.2;
arrayObject.ColumnSpacing = 0.2;

% Update substrate properties 
arrayObject.Element(1).Substrate.Name = 'Air';
arrayObject.Element(1).Substrate.EpsilonR = 1;
arrayObject.Element(1).Substrate.LossTangent = 0;
arrayObject.Element(1).Substrate.Thickness = 0.00199861638666667;

%% Array Analysis 
% Show for rectangularArray
figure;
show(arrayObject) 
% Layout for rectangularArray
figure;
layout(arrayObject) 
% Impedance for rectangularArray
freqRange = 1350000000:15000000:1650000000;
figure;
impedance(arrayObject, freqRange) 
% Pattern for rectangularArray
plotFrequency = 1500000000; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,'Termination',Termination); 
% Azimuth for rectangularArray
plotFrequency = 1500000000; azRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,azRange,0,'Termination',Termination);
% Elevation for rectangularArray
plotFrequency = 1500000000; elRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,0,elRange,'Termination',Termination);
% Sparameters for rectangularArray
freqRange = 1350000000:15000000:1650000000; RefImpedance = 50;
figure;
rfplot(sparameters(arrayObject, freqRange,RefImpedance)); 

